### ISSUE TITLE
ETS: Individual cities pages style / functionality updates

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#462]
### Functionality 

- [x] Turning page title into dropdown for other cities sounds good. 
- [x] Sasha is thinking through link-outs to other "cities pages" at bottom as well; will share mockups

### Style

- [x] Reduce max width of all content to 1200 or 1180px (if the smaller width works, might be preferable)

<img width="501" alt="Screen Shot 2020-06-09 at 3 09 24 PM" src="https://user-images.githubusercontent.com/33635008/84200113-d598b980-aa6b-11ea-9362-32f515a36315.png">

- [x] Align filings column (or entire section) flush right with date
- [x] We’d like to use different “arrow” icons for trends up/down — Sasha will supply

<img width="545" alt="Screen Shot 2020-06-09 at 3 20 13 PM" src="https://user-images.githubusercontent.com/33635008/84200268-1395dd80-aa6c-11ea-9763-6dbed379c58a.png">

_Pic above is edited in browser_

- [x] Increase .section .details h1 font-size to 2.6rem
- [x] section heading h1’s: lighten color to #272727
- [x] Lighten color of body text for greater contrast with headlines (here it is #424242, which passes WCAG on both background colors)

<img width="484" alt="Screen Shot 2020-06-09 at 3 21 37 PM" src="https://user-images.githubusercontent.com/33635008/84200316-24deea00-aa6c-11ea-93e3-74451ad83df1.png">

_Pic above is edited in browser_

- [x] Align .section .footnote left with rest of column (currently superscript numbers exceed the left alignment)
- [x] Decrease max line width to approximately what’s shown

<img width="361" alt="Screen Shot 2020-06-09 at 3 28 47 PM" src="https://user-images.githubusercontent.com/33635008/84200381-493ac680-aa6c-11ea-842d-5f622fcea792.png">

_Pic above is edited in browser_

- [x] suggested "eviction filings" headline style: .`legend-choropleth__title { margin-bottom: 16px; font-size: 1.5rem; font-weight: 800; letter-spacing: 0.12rem; text-transform: uppercase; }`
- [x] suggested date style: `.legend-choropleth__title span { margin-top: 8px; color: #646464; }`
- [x] Can -100% and +100% be moved inward to be flush with ends of legend?

![Screen Shot 2020-06-09 at 3 36 29 PM](https://user-images.githubusercontent.com/33635008/84200399-5788e280-aa6c-11ea-9a45-ed866709b9d5.png)

- [x] Super minor, nice to have, otherwise can live without it: if choropleth is red, can outline be red as well?

![Screen Shot 2020-06-09 at 4 06 39 PM](https://user-images.githubusercontent.com/33635008/84200423-653e6800-aa6c-11ea-8ddc-7f635c75f8a3.png)

- [x] Sasha will provide alternate ideas for this button

**Comment by Lane** [comment]
- [ ] first chart in cities pages: switch default state to “relative to average.” Leave as is for the bottom graph.
